---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "gandi-ddns.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gandi-ddns.name" . }}
    helm.sh/chart: {{ include "gandi-ddns.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "gandi-ddns.name" . }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      template:
        spec:
          restartPolicy: "OnFailure"
          containers:
            - name: "{{ .Chart.Name }}"
              image: "{{.Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: "{{ .Values.image.pullPolicy }}"
              envFrom:
                - configMapRef:
                    name: {{ include "gandi-ddns.fullname" . }}
                - secretRef:
                    name: "{{ .Values.secretName }}"
              resources:
                {{ toYaml .Values.resources | nindent 16 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{ toYaml . | nindent 12 }}
          {{- end }}
